flyway:
  enabled: true
  locations: classpath:migration
  schemas: [test_db]

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    password: Password
    username: root
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true

